title: "Estadística Aplicada"
description: "Materiales del curso de Estadística Aplicada— Luis Fernando Escobar Caba, UAGRM Business School"
url: "https://LFernandoEscobarC.github.io"
baseurl: "/estadistica"

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

markdown: kramdown
exclude:
  - README.md
